import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <Head>
          <title>Link Affiliazione Amazon </title>
          <meta name="description" content="Ottieni il mio link di affiliazione Amazon prima che Mariano distrugga il bottone!" />
          <meta name="keywords" content="Amazon affiliazione, guadagna con Amazon, link di affiliazione, offerte Amazon, minigioco Amazon, Mariano bottone, gioco divertente, Boris" />
          <meta name="author" content="akarakai" />
          <meta property="og:title" content="Link Affiliazione Amazon"/>
          <meta property="og:description" content="Riuscirai a prendere il link di affiliazione Amazon prima che Mariano distrugga il bottone? Gioca ora!" />
          <meta property="og:type" content="website" />
          <meta name="robots" content="index, follow" />
      </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${ubuntu.className}`}>
        {children}
        <Analytics/>
      </body>
    </html>
  );
}
